apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-app-ingress
  labels:
    app.kubernetes.io/name: express-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: main-server-service
                port:
                  number: 80
